# Generated by Django 4.2.11 on 2024-09-21 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BloomLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_name",
                    models.CharField(
                        choices=[
                            ("Remembering", "Remembering"),
                            ("Understanding", "Understanding"),
                            ("Applying", "Applying"),
                            ("Analyzing", "Analyzing"),
                            ("Evaluating", "Evaluating"),
                            ("Creating", "Creating"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "keywords",
                    models.TextField(help_text="Add keywords separated by commas"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=255)),
                ("course_code", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProgramOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_number", models.CharField(max_length=10)),
                ("description", models.TextField()),
                (
                    "bloom_level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pos",
                        to="bloom.bloomlevel",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pos",
                        to="bloom.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("co_number", models.CharField(max_length=10)),
                ("description", models.TextField()),
                (
                    "bloom_level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cos",
                        to="bloom.bloomlevel",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cos",
                        to="bloom.course",
                    ),
                ),
            ],
        ),
    ]
