# Generated by Django 4.2.11 on 2024-09-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bloom", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="courseoutcome", name="bloom_level",),
        migrations.RemoveField(model_name="programoutcome", name="bloom_level",),
    ]
