# Generated by Django 4.2.11 on 2024-09-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloom", "0002_remove_courseoutcome_bloom_level_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bloomlevel", old_name="keywords", new_name="description",
        ),
        migrations.AddField(
            model_name="programoutcome",
            name="course_outcomes",
            field=models.ManyToManyField(
                related_name="program_outcomes", to="bloom.courseoutcome"
            ),
        ),
        migrations.AlterField(
            model_name="course", name="course_code", field=models.TextField(),
        ),
    ]
