# Generated by Django 4.2.10 on 2024-10-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0003_rename_keywords_bloomlevel_description_and_more'),
        ('bloom', '0004_add_question_model'),
    ]

    operations = [
    ]
